#!/usr/bin/env bash -xe
# This may take a long time to run.
mkdir -p profiles

cd "$(dirname $0)"
docker run --rm -it -v "$PWD:/workspace" -w /workspace golang:latest \
    go build -o perfprofile/profile.bin perfprofile/profile.go

python3 perfprofile/perfprofile.py \
    Go/Baseline.go Go/Euler*.go \
    Groovy/Baseline.groovy Groovy/Euler*.groovy \
    Node/Baseline.js Node/Euler*.js \
    Python/Baseline.py Python/Euler00*.py \
    Ruby/Baseline.rb Ruby/Euler*.rb \
    -o profiles/perfprofile.json profiles/perfprofile.yml profiles/perfprofile.csv profiles/perfprofile.md

hwinfo --short --cpu --gfxcard --netcard > profiles/hwinfo.txt
