#!/bin/sh -e

if [ -d /tmp/build ]; then rm -rf /tmp/build; fi
mkdir -p /tmp/build

csdir="/workspace/CSharp/Euler$1"
extras="/workspace/CSharp/Combinatorics"
cp -R $csdir $extras /tmp/build
cd /tmp/build/Euler$1
dotnet run
